version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: certbot
    hostname: certbot
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html

  webhook:
    image: unxsio/unxsbind-webhook
    container_name: unxsbind-webhook
    hostname: $EXTERNAL_WEBHOOK_HOSTNAME
    privileged: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/bin/docker:/usr/bin/docker
      - /root/Docker/Running:/root/Docker/Running:ro
    expose:
      - 8088
    environment:
      - VIRTUAL_HOST=$EXTERNAL_WEBHOOK_HOSTNAME
      - LETSENCRYPT_HOST=$EXTERNAL_WEBHOOK_HOSTNAME
      - LETSENCRYPT_EMAIL=certbot@unxs.io

networks:
  default:
    external:
      name: docker_default
